const { query } = require('../config/database');

const sampleProperties = [
  {
    parcelNumber: 'TX-TRAVIS-2024-001',
    address: '123 Main Street',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    propertyType: 'single-family',
    bedrooms: 3,
    bathrooms: 1,
    squareFeet: 1200,
    lotSizeSqft: 6000,
    yearBuilt: 1975,
    condition: 'poor',
    taxAssessedValue: 180000,
    zestimate: 250000,
    lastSalePrice: 150000,
    lastSaleDate: '2023-06-15',
    ownerName: 'John Smith',
    ownerType: 'individual',
    latitude: 30.2672,
    longitude: -97.7431,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-TRAVIS-2024-002',
    address: '456 Oak Avenue',
    city: 'Austin',
    state: 'TX',
    zipCode: '78702',
    propertyType: 'single-family',
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1800,
    lotSizeSqft: 8000,
    yearBuilt: 1985,
    condition: 'fair',
    taxAssessedValue: 320000,
    zestimate: 380000,
    lastSalePrice: 280000,
    lastSaleDate: '2022-03-20',
    ownerName: 'Jane Doe',
    ownerType: 'investor',
    latitude: 30.28,
    longitude: -97.75,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-TRAVIS-2024-003',
    address: '789 Elm Road',
    city: 'Austin',
    state: 'TX',
    zipCode: '78703',
    propertyType: 'multi-family',
    bedrooms: 6,
    bathrooms: 3,
    squareFeet: 2200,
    lotSizeSqft: 10000,
    yearBuilt: 1995,
    condition: 'good',
    taxAssessedValue: 520000,
    zestimate: 580000,
    lastSalePrice: 480000,
    lastSaleDate: '2021-11-10',
    ownerName: 'Investment Corp',
    ownerType: 'corporation',
    latitude: 30.295,
    longitude: -97.735,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-TRAVIS-2024-004',
    address: '321 Pine Lane',
    city: 'Austin',
    state: 'TX',
    zipCode: '78704',
    propertyType: 'single-family',
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 950,
    lotSizeSqft: 5000,
    yearBuilt: 1970,
    condition: 'poor',
    taxAssessedValue: 140000,
    zestimate: 200000,
    lastSalePrice: 110000,
    lastSaleDate: '2023-01-05',
    ownerName: 'Mary Johnson',
    ownerType: 'individual',
    latitude: 30.26,
    longitude: -97.76,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-TRAVIS-2024-005',
    address: '654 Maple Drive',
    city: 'Austin',
    state: 'TX',
    zipCode: '78705',
    propertyType: 'single-family',
    bedrooms: 5,
    bathrooms: 3,
    squareFeet: 2500,
    lotSizeSqft: 12000,
    yearBuilt: 2005,
    condition: 'excellent',
    taxAssessedValue: 650000,
    zestimate: 700000,
    lastSalePrice: 620000,
    lastSaleDate: '2022-08-14',
    ownerName: 'Robert Wilson',
    ownerType: 'individual',
    latitude: 30.3,
    longitude: -97.72,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-DALLAS-2024-001',
    address: '111 Commerce Street',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    propertyType: 'single-family',
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1600,
    lotSizeSqft: 7000,
    yearBuilt: 1990,
    condition: 'fair',
    taxAssessedValue: 280000,
    zestimate: 320000,
    lastSalePrice: 250000,
    lastSaleDate: '2023-02-22',
    ownerName: 'Bank of America',
    ownerType: 'bank',
    latitude: 32.7767,
    longitude: -96.797,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-DALLAS-2024-002',
    address: '222 Market Lane',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75202',
    propertyType: 'multi-family',
    bedrooms: 8,
    bathrooms: 4,
    squareFeet: 3000,
    lotSizeSqft: 15000,
    yearBuilt: 2000,
    condition: 'good',
    taxAssessedValue: 580000,
    zestimate: 640000,
    lastSalePrice: 550000,
    lastSaleDate: '2021-07-11',
    ownerName: 'Property Management LLC',
    ownerType: 'corporation',
    latitude: 32.79,
    longitude: -96.78,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-HARRIS-2024-001',
    address: '555 Energy Avenue',
    city: 'Houston',
    state: 'TX',
    zipCode: '77001',
    propertyType: 'single-family',
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1900,
    lotSizeSqft: 8500,
    yearBuilt: 2010,
    condition: 'good',
    taxAssessedValue: 420000,
    zestimate: 480000,
    lastSalePrice: 400000,
    lastSaleDate: '2022-05-30',
    ownerName: 'Sarah Martinez',
    ownerType: 'investor',
    latitude: 29.7604,
    longitude: -95.3698,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'TX-HARRIS-2024-002',
    address: '777 Space Center Drive',
    city: 'Houston',
    state: 'TX',
    zipCode: '77002',
    propertyType: 'vacant-land',
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 0,
    lotSizeSqft: 20000,
    yearBuilt: null,
    condition: 'good',
    taxAssessedValue: 150000,
    zestimate: 180000,
    lastSalePrice: 140000,
    lastSaleDate: '2023-04-18',
    ownerName: 'Development Partners',
    ownerType: 'corporation',
    latitude: 29.75,
    longitude: -95.36,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'FL-MIAMI-DADE-2024-001',
    address: '100 Biscayne Boulevard',
    city: 'Miami',
    state: 'FL',
    zipCode: '33132',
    propertyType: 'single-family',
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1650,
    lotSizeSqft: 7200,
    yearBuilt: 1988,
    condition: 'fair',
    taxAssessedValue: 425000,
    zestimate: 510000,
    lastSalePrice: 390000,
    lastSaleDate: '2023-09-12',
    ownerName: 'Carlos Rivera',
    ownerType: 'individual',
    latitude: 25.7753,
    longitude: -80.1889,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'FL-HILLSBOROUGH-2024-001',
    address: '420 Bay Street',
    city: 'Tampa',
    state: 'FL',
    zipCode: '33602',
    propertyType: 'single-family',
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 2100,
    lotSizeSqft: 9000,
    yearBuilt: 1998,
    condition: 'good',
    taxAssessedValue: 385000,
    zestimate: 445000,
    lastSalePrice: 360000,
    lastSaleDate: '2022-11-03',
    ownerName: 'Lisa Thompson',
    ownerType: 'investor',
    latitude: 27.9475,
    longitude: -82.4584,
    dataSource: 'seed'
  },
  {
    parcelNumber: 'FL-ORANGE-2024-001',
    address: '800 Orange Avenue',
    city: 'Orlando',
    state: 'FL',
    zipCode: '32801',
    propertyType: 'multi-family',
    bedrooms: 6,
    bathrooms: 3,
    squareFeet: 2800,
    lotSizeSqft: 11000,
    yearBuilt: 2005,
    condition: 'good',
    taxAssessedValue: 520000,
    zestimate: 590000,
    lastSalePrice: 495000,
    lastSaleDate: '2021-04-22',
    ownerName: 'Sunshine Holdings LLC',
    ownerType: 'corporation',
    latitude: 28.5383,
    longitude: -81.3792,
    dataSource: 'seed'
  }
];

async function seed() {
  console.log('Seeding properties...');
  let inserted = 0;

  for (const prop of sampleProperties) {
    const {
      parcelNumber, address, city, state, zipCode, propertyType,
      bedrooms, bathrooms, squareFeet, lotSizeSqft, yearBuilt,
      condition, taxAssessedValue, zestimate, lastSalePrice, lastSaleDate,
      ownerName, ownerType, latitude, longitude, dataSource
    } = prop;

    const result = await query(
      `INSERT INTO properties (
        parcel_number, address, city, state, zip_code, property_type,
        bedrooms, bathrooms, square_feet, lot_size_sqft, year_built,
        condition, tax_assessed_value, zestimate, last_sale_price, last_sale_date,
        owner_name, owner_type, latitude, longitude, data_source
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
      ON CONFLICT (parcel_number) DO NOTHING
      RETURNING id`,
      [parcelNumber, address, city, state, zipCode, propertyType,
        bedrooms, bathrooms, squareFeet, lotSizeSqft, yearBuilt,
        condition, taxAssessedValue, zestimate, lastSalePrice, lastSaleDate,
        ownerName, ownerType, latitude, longitude, dataSource]
    );

    if (result.rows.length > 0) inserted += 1;
  }

  console.log(`Seeded ${inserted} properties`);
  return inserted;
}

if (require.main === module) {
  seed().then(() => process.exit(0)).catch((err) => {
    console.error(err.message);
    process.exit(1);
  });
}

module.exports = { seed, sampleProperties };
